# -*- coding: utf-8 -*-

# Form implementation generated from sconcho.gui.reading ui file 'ui/main_window.ui'
#
# Created: Thu May  2 22:42:15 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1081, 716)
        MainWindow.setWindowTitle(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sconcho_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.infoLayout = QtGui.QHBoxLayout()
        self.infoLayout.setObjectName(_fromUtf8("infoLayout"))
        self.activeSymbolWidget = ActiveSymbolWidget(self.centralwidget)
        self.activeSymbolWidget.setObjectName(_fromUtf8("activeSymbolWidget"))
        self.infoLayout.addWidget(self.activeSymbolWidget)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.infoLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.infoLayout)
        self.graphicsView = PatternView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsView.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout.addWidget(self.graphicsView)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 694, 71))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.colorWidget = ColorWidget(self.scrollAreaWidgetContents)
        self.colorWidget.setObjectName(_fromUtf8("colorWidget"))
        self.verticalLayout_4.addWidget(self.colorWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecent_Files = QtGui.QMenu(self.menuFile)
        self.menuRecent_Files.setObjectName(_fromUtf8("menuRecent_Files"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menu_Zoom = QtGui.QMenu(self.menuView)
        self.menu_Zoom.setObjectName(_fromUtf8("menu_Zoom"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuGrid = QtGui.QMenu(self.menubar)
        self.menuGrid.setObjectName(_fromUtf8("menuGrid"))
        self.menu_Resize_Grid = QtGui.QMenu(self.menubar)
        self.menu_Resize_Grid.setObjectName(_fromUtf8("menu_Resize_Grid"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.symbolDockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.symbolDockWidget.sizePolicy().hasHeightForWidth())
        self.symbolDockWidget.setSizePolicy(sizePolicy)
        self.symbolDockWidget.setMinimumSize(QtCore.QSize(359, 239))
        self.symbolDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.symbolDockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.symbolDockWidget.setObjectName(_fromUtf8("symbolDockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.SymbolSelectorSplitter = QtGui.QSplitter(self.dockWidgetContents_3)
        self.SymbolSelectorSplitter.setOrientation(QtCore.Qt.Vertical)
        self.SymbolSelectorSplitter.setObjectName(_fromUtf8("SymbolSelectorSplitter"))
        self.layoutWidget = QtGui.QWidget(self.SymbolSelectorSplitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.symbolSelectorLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.symbolSelectorLayout.setMargin(0)
        self.symbolSelectorLayout.setObjectName(_fromUtf8("symbolSelectorLayout"))
        self.symbolCategoryChooser = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.symbolCategoryChooser.sizePolicy().hasHeightForWidth())
        self.symbolCategoryChooser.setSizePolicy(sizePolicy)
        self.symbolCategoryChooser.setObjectName(_fromUtf8("symbolCategoryChooser"))
        self.symbolSelectorLayout.addWidget(self.symbolCategoryChooser)
        self.layoutWidget1 = QtGui.QWidget(self.SymbolSelectorSplitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.clearFrequentlyUsedSymbolsButton = QtGui.QPushButton(self.layoutWidget1)
        self.clearFrequentlyUsedSymbolsButton.setObjectName(_fromUtf8("clearFrequentlyUsedSymbolsButton"))
        self.horizontalLayout.addWidget(self.clearFrequentlyUsedSymbolsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea_2 = QtGui.QScrollArea(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 333, 120))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.recentlyUsedSymbolWidget = RecentlyUsedSymbolWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recentlyUsedSymbolWidget.sizePolicy().hasHeightForWidth())
        self.recentlyUsedSymbolWidget.setSizePolicy(sizePolicy)
        self.recentlyUsedSymbolWidget.setObjectName(_fromUtf8("recentlyUsedSymbolWidget"))
        self.horizontalLayout_2.addWidget(self.recentlyUsedSymbolWidget)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.SymbolSelectorSplitter)
        self.symbolDockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.symbolDockWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionAbout_sconcho = QtGui.QAction(MainWindow)
        self.actionAbout_sconcho.setIcon(icon)
        self.actionAbout_sconcho.setObjectName(_fromUtf8("actionAbout_sconcho"))
        self.actionAbout_Qt4 = QtGui.QAction(MainWindow)
        self.actionAbout_Qt4.setObjectName(_fromUtf8("actionAbout_Qt4"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filesaveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon4)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionExport = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fileexport.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon5)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon6)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPrint = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fileprint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon7)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionShow_pattern_grid = QtGui.QAction(MainWindow)
        self.actionShow_pattern_grid.setCheckable(True)
        self.actionShow_pattern_grid.setChecked(True)
        self.actionShow_pattern_grid.setObjectName(_fromUtf8("actionShow_pattern_grid"))
        self.actionShow_legend = QtGui.QAction(MainWindow)
        self.actionShow_legend.setCheckable(True)
        self.actionShow_legend.setChecked(True)
        self.actionShow_legend.setObjectName(_fromUtf8("actionShow_legend"))
        self.actionShow_row_labels = QtGui.QAction(MainWindow)
        self.actionShow_row_labels.setCheckable(True)
        self.actionShow_row_labels.setChecked(True)
        self.actionShow_row_labels.setObjectName(_fromUtf8("actionShow_row_labels"))
        self.action_Insert_delete_rows_and_columns = QtGui.QAction(MainWindow)
        self.action_Insert_delete_rows_and_columns.setObjectName(_fromUtf8("action_Insert_delete_rows_and_columns"))
        self.actionZoom_In = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon8)
        self.actionZoom_In.setObjectName(_fromUtf8("actionZoom_In"))
        self.actionZoom_Out = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon9)
        self.actionZoom_Out.setObjectName(_fromUtf8("actionZoom_Out"))
        self.actionFit = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-best-fit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFit.setIcon(icon10)
        self.actionFit.setObjectName(_fromUtf8("actionFit"))
        self.actionSconcho_Manual = QtGui.QAction(MainWindow)
        self.actionSconcho_Manual.setIcon(icon)
        self.actionSconcho_Manual.setObjectName(_fromUtf8("actionSconcho_Manual"))
        self.actionPrefs = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gtk-preferences.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrefs.setIcon(icon11)
        self.actionPrefs.setObjectName(_fromUtf8("actionPrefs"))
        self.action_Insert_delete_rows_and_columns1 = QtGui.QAction(MainWindow)
        self.action_Insert_delete_rows_and_columns1.setObjectName(_fromUtf8("action_Insert_delete_rows_and_columns1"))
        self.action_Manage_Knitting_Symbols = QtGui.QAction(MainWindow)
        self.action_Manage_Knitting_Symbols.setObjectName(_fromUtf8("action_Manage_Knitting_Symbols"))
        self.actionUnselect_All = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gtk-clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnselect_All.setIcon(icon12)
        self.actionUnselect_All.setObjectName(_fromUtf8("actionUnselect_All"))
        self.action_Copy = QtGui.QAction(MainWindow)
        self.action_Copy.setObjectName(_fromUtf8("action_Copy"))
        self.action_Paste = QtGui.QAction(MainWindow)
        self.action_Paste.setObjectName(_fromUtf8("action_Paste"))
        self.actionCheck_Pattern_Grid = QtGui.QAction(MainWindow)
        self.actionCheck_Pattern_Grid.setObjectName(_fromUtf8("actionCheck_Pattern_Grid"))
        self.action_Normal = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zoom-original.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Normal.setIcon(icon13)
        self.action_Normal.setObjectName(_fromUtf8("action_Normal"))
        self.action_Undo = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Undo.setIcon(icon14)
        self.action_Undo.setObjectName(_fromUtf8("action_Undo"))
        self.action_Redo = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Redo.setIcon(icon15)
        self.action_Redo.setObjectName(_fromUtf8("action_Redo"))
        self.actionShow_nostitch_symbols = QtGui.QAction(MainWindow)
        self.actionShow_nostitch_symbols.setCheckable(True)
        self.actionShow_nostitch_symbols.setChecked(True)
        self.actionShow_nostitch_symbols.setObjectName(_fromUtf8("actionShow_nostitch_symbols"))
        self.actionCreate_Pattern_Repeat = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pattern_repeat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Pattern_Repeat.setIcon(icon16)
        self.actionCreate_Pattern_Repeat.setObjectName(_fromUtf8("actionCreate_Pattern_Repeat"))
        self.actionApply_Color_to_Selection = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApply_Color_to_Selection.setIcon(icon17)
        self.actionApply_Color_to_Selection.setObjectName(_fromUtf8("actionApply_Color_to_Selection"))
        self.actionCheck_for_updates = QtGui.QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName(_fromUtf8("actionCheck_for_updates"))
        self.actionPrint_Preview = QtGui.QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(_fromUtf8("actionPrint_Preview"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_Clear_Recently_Used_Files = QtGui.QAction(MainWindow)
        self.action_Clear_Recently_Used_Files.setObjectName(_fromUtf8("action_Clear_Recently_Used_Files"))
        self.actionAdd_Row_Repeat = QtGui.QAction(MainWindow)
        self.actionAdd_Row_Repeat.setObjectName(_fromUtf8("actionAdd_Row_Repeat"))
        self.actionShow_column_labels = QtGui.QAction(MainWindow)
        self.actionShow_column_labels.setCheckable(True)
        self.actionShow_column_labels.setChecked(True)
        self.actionShow_column_labels.setObjectName(_fromUtf8("actionShow_column_labels"))
        self.actionAdd_Text = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Text.setIcon(icon18)
        self.actionAdd_Text.setObjectName(_fromUtf8("actionAdd_Text"))
        self.actionDelete_rows = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete_row.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_rows.setIcon(icon19)
        self.actionDelete_rows.setObjectName(_fromUtf8("actionDelete_rows"))
        self.actionInsert_rows = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/insert_row.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert_rows.setIcon(icon20)
        self.actionInsert_rows.setObjectName(_fromUtf8("actionInsert_rows"))
        self.actionDelete_columns = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete_column.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_columns.setIcon(icon21)
        self.actionDelete_columns.setObjectName(_fromUtf8("actionDelete_columns"))
        self.actionInsert_columns = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/insert_column.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsert_columns.setIcon(icon22)
        self.actionInsert_columns.setObjectName(_fromUtf8("actionInsert_columns"))
        self.actionCreate_Row_Repeat = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/row_repeats.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Row_Repeat.setIcon(icon23)
        self.actionCreate_Row_Repeat.setObjectName(_fromUtf8("actionCreate_Row_Repeat"))
        self.action_Copy_Rectangular_Selection = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Copy_Rectangular_Selection.setIcon(icon24)
        self.action_Copy_Rectangular_Selection.setObjectName(_fromUtf8("action_Copy_Rectangular_Selection"))
        self.action_Paste_Rectangular_Selection = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/paste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Paste_Rectangular_Selection.setIcon(icon25)
        self.action_Paste_Rectangular_Selection.setObjectName(_fromUtf8("action_Paste_Rectangular_Selection"))
        self.actionHide_Selected_Cells = QtGui.QAction(MainWindow)
        self.actionHide_Selected_Cells.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/hide_cells.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_Selected_Cells.setIcon(icon26)
        self.actionHide_Selected_Cells.setObjectName(_fromUtf8("actionHide_Selected_Cells"))
        self.actionShow_Selected_Cells = QtGui.QAction(MainWindow)
        self.actionShow_Selected_Cells.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/show_cells.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Selected_Cells.setIcon(icon27)
        self.actionShow_Selected_Cells.setObjectName(_fromUtf8("actionShow_Selected_Cells"))
        self.actionCreate_Chart = QtGui.QAction(MainWindow)
        self.actionCreate_Chart.setCheckable(True)
        self.actionCreate_Chart.setChecked(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/create_cells.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Chart.setIcon(icon28)
        self.actionCreate_Chart.setObjectName(_fromUtf8("actionCreate_Chart"))
        self.menuRecent_Files.addAction(self.action_Clear_Recently_Used_Files)
        self.menuRecent_Files.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuRecent_Files.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menu_Zoom.addAction(self.actionZoom_In)
        self.menu_Zoom.addAction(self.actionZoom_Out)
        self.menu_Zoom.addAction(self.actionFit)
        self.menu_Zoom.addAction(self.action_Normal)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menu_Zoom.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShow_pattern_grid)
        self.menuView.addAction(self.actionShow_legend)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionCreate_Chart)
        self.menuView.addAction(self.actionShow_Selected_Cells)
        self.menuView.addAction(self.actionHide_Selected_Cells)
        self.menuHelp.addAction(self.actionSconcho_Manual)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheck_for_updates)
        self.menuHelp.addAction(self.actionAbout_sconcho)
        self.menuHelp.addAction(self.actionAbout_Qt4)
        self.menuGrid.addSeparator()
        self.menuGrid.addAction(self.action_Undo)
        self.menuGrid.addAction(self.action_Redo)
        self.menuGrid.addSeparator()
        self.menuGrid.addAction(self.action_Copy_Rectangular_Selection)
        self.menuGrid.addAction(self.action_Paste_Rectangular_Selection)
        self.menuGrid.addSeparator()
        self.menuGrid.addAction(self.action_Manage_Knitting_Symbols)
        self.menuGrid.addSeparator()
        self.menuGrid.addAction(self.actionPrefs)
        self.menu_Resize_Grid.addAction(self.actionDelete_rows)
        self.menu_Resize_Grid.addAction(self.actionInsert_rows)
        self.menu_Resize_Grid.addAction(self.actionDelete_columns)
        self.menu_Resize_Grid.addAction(self.actionInsert_columns)
        self.menuTools.addAction(self.actionUnselect_All)
        self.menuTools.addAction(self.actionCreate_Pattern_Repeat)
        self.menuTools.addAction(self.actionApply_Color_to_Selection)
        self.menuTools.addAction(self.actionAdd_Text)
        self.menuTools.addAction(self.actionCreate_Row_Repeat)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGrid.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menu_Resize_Grid.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Redo)
        self.toolBar.addAction(self.action_Undo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_In)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addAction(self.actionFit)
        self.toolBar.addAction(self.action_Normal)
        self.toolBar_2.addAction(self.actionUnselect_All)
        self.toolBar_2.addAction(self.actionCreate_Pattern_Repeat)
        self.toolBar_2.addAction(self.actionApply_Color_to_Selection)
        self.toolBar_2.addAction(self.actionAdd_Text)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionDelete_rows)
        self.toolBar_2.addAction(self.actionInsert_rows)
        self.toolBar_2.addAction(self.actionDelete_columns)
        self.toolBar_2.addAction(self.actionInsert_columns)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.actionCreate_Chart)
        self.toolBar_2.addAction(self.actionShow_Selected_Cells)
        self.toolBar_2.addAction(self.actionHide_Selected_Cells)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuRecent_Files.setTitle(_translate("MainWindow", "Recent Files", None))
        self.menuView.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Zoom.setTitle(_translate("MainWindow", "&Zoom", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.menuGrid.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_Resize_Grid.setTitle(_translate("MainWindow", "&Resize Grid", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.symbolDockWidget.setWindowTitle(_translate("MainWindow", "sconcho: available knitting symbols", None))
        self.label.setText(_translate("MainWindow", "Frequently Used Symbols", None))
        self.clearFrequentlyUsedSymbolsButton.setText(_translate("MainWindow", "Clear List", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.actionAbout_sconcho.setText(_translate("MainWindow", "About sconcho", None))
        self.actionAbout_Qt4.setText(_translate("MainWindow", "About Qt4", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionNew.setText(_translate("MainWindow", "&New...", None))
        self.actionNew.setToolTip(_translate("MainWindow", "Start New Chart", None))
        self.actionNew.setStatusTip(_translate("MainWindow", "Start New Chart", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open...", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open saved project", None))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open saved project", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save project", None))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save project", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save  &as...", None))
        self.actionSave_as.setToolTip(_translate("MainWindow", "Save project as", None))
        self.actionSave_as.setStatusTip(_translate("MainWindow", "Save project as", None))
        self.actionExport.setText(_translate("MainWindow", "&Export ...", None))
        self.actionExport.setToolTip(_translate("MainWindow", "Export as image file", None))
        self.actionExport.setStatusTip(_translate("MainWindow", "Export as image file", None))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionQuit.setToolTip(_translate("MainWindow", "Quit sconcho", None))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit sconcho", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionPrint.setText(_translate("MainWindow", "&Print...", None))
        self.actionPrint.setStatusTip(_translate("MainWindow", "Print", None))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionShow_pattern_grid.setText(_translate("MainWindow", "Show &Pattern Grid", None))
        self.actionShow_pattern_grid.setToolTip(_translate("MainWindow", "toggle visibility of pattern grid", None))
        self.actionShow_pattern_grid.setStatusTip(_translate("MainWindow", "toggle visibility of pattern ", None))
        self.actionShow_legend.setText(_translate("MainWindow", "Show &Legend", None))
        self.actionShow_legend.setToolTip(_translate("MainWindow", "toggle visibility of legend", None))
        self.actionShow_legend.setStatusTip(_translate("MainWindow", "toggle visibility of legend", None))
        self.actionShow_row_labels.setText(_translate("MainWindow", "Show &Row Labels", None))
        self.actionShow_row_labels.setToolTip(_translate("MainWindow", "toggle visbility of grid labels", None))
        self.actionShow_row_labels.setStatusTip(_translate("MainWindow", "toggle visbility of grid labels", None))
        self.action_Insert_delete_rows_and_columns.setText(_translate("MainWindow", "&Insert/Delete Rows and Columns", None))
        self.action_Insert_delete_rows_and_columns.setStatusTip(_translate("MainWindow", "insert/delete rows and columns", None))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom &In", None))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom &Out", None))
        self.actionFit.setText(_translate("MainWindow", "&Fit", None))
        self.actionSconcho_Manual.setText(_translate("MainWindow", "Sconcho Manual", None))
        self.actionPrefs.setText(_translate("MainWindow", "P&references", None))
        self.action_Insert_delete_rows_and_columns1.setText(_translate("MainWindow", "&Manage Grid", None))
        self.action_Manage_Knitting_Symbols.setText(_translate("MainWindow", "&Manage Custom Knitting Symbols", None))
        self.actionUnselect_All.setText(_translate("MainWindow", "&Deselect All", None))
        self.actionUnselect_All.setToolTip(_translate("MainWindow", "Deselect all currently highlighted cells on the grid.", None))
        self.actionUnselect_All.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.action_Copy.setText(_translate("MainWindow", "&Copy", None))
        self.action_Paste.setText(_translate("MainWindow", "&Paste", None))
        self.actionCheck_Pattern_Grid.setText(_translate("MainWindow", "Check Pattern Grid", None))
        self.actionCheck_Pattern_Grid.setToolTip(_translate("MainWindow", "Chech Pattern Grid", None))
        self.action_Normal.setText(_translate("MainWindow", "&Normal", None))
        self.action_Undo.setText(_translate("MainWindow", "&Undo", None))
        self.action_Undo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.action_Redo.setText(_translate("MainWindow", "&Redo", None))
        self.action_Redo.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionShow_nostitch_symbols.setText(_translate("MainWindow", "Show &Nostitch Symbols", None))
        self.actionCreate_Pattern_Repeat.setText(_translate("MainWindow", "&Create Pattern Repeat", None))
        self.actionCreate_Pattern_Repeat.setToolTip(_translate("MainWindow", "Create a pattern repeat box around the currently highlighted cells.", None))
        self.actionApply_Color_to_Selection.setText(_translate("MainWindow", "&Apply Color to Selection", None))
        self.actionApply_Color_to_Selection.setToolTip(_translate("MainWindow", "Apply Color to Selection. Applies the currently selected color to all highlighted cells on the canvas.", None))
        self.actionCheck_for_updates.setText(_translate("MainWindow", "Check for updates", None))
        self.actionPrint_Preview.setText(_translate("MainWindow", "Print Preview...", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.action.setText(_translate("MainWindow", "Clear List", None))
        self.action_Clear_Recently_Used_Files.setText(_translate("MainWindow", "&Clear", None))
        self.action_Clear_Recently_Used_Files.setStatusTip(_translate("MainWindow", "Clear the list of recent items.", None))
        self.actionAdd_Row_Repeat.setText(_translate("MainWindow", "&Add Row Repeat", None))
        self.actionShow_column_labels.setText(_translate("MainWindow", "Show &Column Labels", None))
        self.actionAdd_Text.setText(_translate("MainWindow", "Add &Text Box", None))
        self.actionDelete_rows.setText(_translate("MainWindow", "&Delete Selected Rows", None))
        self.actionInsert_rows.setText(_translate("MainWindow", "Insert &Rows", None))
        self.actionDelete_columns.setText(_translate("MainWindow", "Delete &Selected Columns", None))
        self.actionInsert_columns.setText(_translate("MainWindow", "Insert &Columns", None))
        self.actionCreate_Row_Repeat.setText(_translate("MainWindow", "Create &Row Repeat", None))
        self.action_Copy_Rectangular_Selection.setText(_translate("MainWindow", "&Copy", None))
        self.action_Copy_Rectangular_Selection.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.action_Paste_Rectangular_Selection.setText(_translate("MainWindow", "&Paste ", None))
        self.action_Paste_Rectangular_Selection.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.actionHide_Selected_Cells.setText(_translate("MainWindow", "&Hide Selected Cells", None))
        self.actionShow_Selected_Cells.setText(_translate("MainWindow", "&Unhide Selected Cells", None))
        self.actionCreate_Chart.setText(_translate("MainWindow", "&Create Chart", None))

from sconcho.gui.recently_used_symbol_widget import RecentlyUsedSymbolWidget
from sconcho.gui.active_symbol_widget import ActiveSymbolWidget
from sconcho.gui.color_widget import ColorWidget
from sconcho.gui.pattern_view import PatternView
from . import icons_rc
