# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/manageKnittingSymbolDialog.ui'
#
# Created: Mon Jan 17 17:37:46 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ManageKnittingSymbolDialog(object):
    def setupUi(self, ManageKnittingSymbolDialog):
        ManageKnittingSymbolDialog.setObjectName("ManageKnittingSymbolDialog")
        ManageKnittingSymbolDialog.resize(753, 660)
        self.verticalLayout_5 = QtGui.QVBoxLayout(ManageKnittingSymbolDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(ManageKnittingSymbolDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.availableSymbolsWidget = QtGui.QTreeWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.availableSymbolsWidget.sizePolicy().hasHeightForWidth())
        self.availableSymbolsWidget.setSizePolicy(sizePolicy)
        self.availableSymbolsWidget.setColumnCount(1)
        self.availableSymbolsWidget.setObjectName("availableSymbolsWidget")
        self.verticalLayout.addWidget(self.availableSymbolsWidget)
        self.addSymbolButton = QtGui.QPushButton(self.frame)
        self.addSymbolButton.setObjectName("addSymbolButton")
        self.verticalLayout.addWidget(self.addSymbolButton)
        self.updateSymbolButton = QtGui.QPushButton(self.frame)
        self.updateSymbolButton.setEnabled(False)
        self.updateSymbolButton.setObjectName("updateSymbolButton")
        self.verticalLayout.addWidget(self.updateSymbolButton)
        self.deleteSymbolButton = QtGui.QPushButton(self.frame)
        self.deleteSymbolButton.setEnabled(False)
        self.deleteSymbolButton.setObjectName("deleteSymbolButton")
        self.verticalLayout.addWidget(self.deleteSymbolButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.frame)
        self.symbolEntryFrame = QtGui.QFrame(ManageKnittingSymbolDialog)
        self.symbolEntryFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.symbolEntryFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.symbolEntryFrame.setObjectName("symbolEntryFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.symbolEntryFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtGui.QLabel(self.symbolEntryFrame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.symbolPreviewFrame = QtGui.QFrame(self.symbolEntryFrame)
        self.symbolPreviewFrame.setMinimumSize(QtCore.QSize(100, 60))
        self.symbolPreviewFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.symbolPreviewFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.symbolPreviewFrame.setObjectName("symbolPreviewFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.symbolPreviewFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.svgWidget = QSvgWidget(self.symbolPreviewFrame)
        self.svgWidget.setObjectName("svgWidget")
        self.horizontalLayout_2.addWidget(self.svgWidget)
        self.horizontalLayout_8.addWidget(self.symbolPreviewFrame)
        self.svgPathEdit = QtGui.QLineEdit(self.symbolEntryFrame)
        self.svgPathEdit.setReadOnly(False)
        self.svgPathEdit.setObjectName("svgPathEdit")
        self.horizontalLayout_8.addWidget(self.svgPathEdit)
        self.browseSymbolButton = QtGui.QPushButton(self.symbolEntryFrame)
        self.browseSymbolButton.setEnabled(True)
        self.browseSymbolButton.setAutoDefault(False)
        self.browseSymbolButton.setObjectName("browseSymbolButton")
        self.horizontalLayout_8.addWidget(self.browseSymbolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_12 = QtGui.QLabel(self.symbolEntryFrame)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.symbolNameLabel = QtGui.QLabel(self.symbolEntryFrame)
        self.symbolNameLabel.setEnabled(True)
        self.symbolNameLabel.setObjectName("symbolNameLabel")
        self.gridLayout_3.addWidget(self.symbolNameLabel, 0, 0, 1, 1)
        self.symbolNameEntry = QtGui.QLineEdit(self.symbolEntryFrame)
        self.symbolNameEntry.setReadOnly(False)
        self.symbolNameEntry.setObjectName("symbolNameEntry")
        self.gridLayout_3.addWidget(self.symbolNameEntry, 0, 1, 1, 1)
        self.symbolCategoryLabel = QtGui.QLabel(self.symbolEntryFrame)
        self.symbolCategoryLabel.setEnabled(True)
        self.symbolCategoryLabel.setObjectName("symbolCategoryLabel")
        self.gridLayout_3.addWidget(self.symbolCategoryLabel, 1, 0, 1, 1)
        self.symbolWidthLabel = QtGui.QLabel(self.symbolEntryFrame)
        self.symbolWidthLabel.setEnabled(True)
        self.symbolWidthLabel.setObjectName("symbolWidthLabel")
        self.gridLayout_3.addWidget(self.symbolWidthLabel, 3, 0, 1, 1)
        self.symbolWidthSpinner = QtGui.QSpinBox(self.symbolEntryFrame)
        self.symbolWidthSpinner.setEnabled(True)
        self.symbolWidthSpinner.setReadOnly(False)
        self.symbolWidthSpinner.setMinimum(1)
        self.symbolWidthSpinner.setObjectName("symbolWidthSpinner")
        self.gridLayout_3.addWidget(self.symbolWidthSpinner, 3, 1, 1, 1)
        self.symbolDescriptionLabel = QtGui.QLabel(self.symbolEntryFrame)
        self.symbolDescriptionLabel.setEnabled(True)
        self.symbolDescriptionLabel.setObjectName("symbolDescriptionLabel")
        self.gridLayout_3.addWidget(self.symbolDescriptionLabel, 4, 0, 1, 1)
        self.symbolDescriptionEntry = QtGui.QTextEdit(self.symbolEntryFrame)
        self.symbolDescriptionEntry.setReadOnly(False)
        self.symbolDescriptionEntry.setObjectName("symbolDescriptionEntry")
        self.gridLayout_3.addWidget(self.symbolDescriptionEntry, 4, 1, 1, 1)
        self.categoryChooser = QtGui.QComboBox(self.symbolEntryFrame)
        self.categoryChooser.setObjectName("categoryChooser")
        self.gridLayout_3.addWidget(self.categoryChooser, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cancelButton = QtGui.QPushButton(self.symbolEntryFrame)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.actionButton = QtGui.QPushButton(self.symbolEntryFrame)
        self.actionButton.setObjectName("actionButton")
        self.horizontalLayout_3.addWidget(self.actionButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.symbolEntryFrame)
        spacerItem3 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_4 = QtGui.QPushButton(ManageKnittingSymbolDialog)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.symbolNameLabel.setBuddy(self.symbolNameEntry)
        self.symbolCategoryLabel.setBuddy(self.categoryChooser)
        self.symbolWidthLabel.setBuddy(self.symbolWidthSpinner)
        self.symbolDescriptionLabel.setBuddy(self.symbolDescriptionEntry)

        self.retranslateUi(ManageKnittingSymbolDialog)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL("clicked()"), ManageKnittingSymbolDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ManageKnittingSymbolDialog)

    def retranslateUi(self, ManageKnittingSymbolDialog):
        ManageKnittingSymbolDialog.setWindowTitle(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "sconcho: Manage Custom Knitting Symbols", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Available Symbols</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.availableSymbolsWidget.headerItem().setText(0, QtGui.QApplication.translate("ManageKnittingSymbolDialog", "Category/Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.addSymbolButton.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "&Add New Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.updateSymbolButton.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "Update Selected Symbol ", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteSymbolButton.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "&Delete Selected Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">SVG Image</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.browseSymbolButton.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "&Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Description</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.symbolNameLabel.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "symbol &name", None, QtGui.QApplication.UnicodeUTF8))
        self.symbolCategoryLabel.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "symbol &category", None, QtGui.QApplication.UnicodeUTF8))
        self.symbolWidthLabel.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "symbol &width", None, QtGui.QApplication.UnicodeUTF8))
        self.symbolDescriptionLabel.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "symbol &description", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionButton.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("ManageKnittingSymbolDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4.QtSvg import QSvgWidget
