# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/pattern_row_repeat_editor_dialog.ui'
#
# Created: Tue Dec  6 09:27:02 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PatternRowRepeatEditor(object):
    def setupUi(self, PatternRowRepeatEditor):
        PatternRowRepeatEditor.setObjectName(_fromUtf8("PatternRowRepeatEditor"))
        PatternRowRepeatEditor.resize(533, 495)
        PatternRowRepeatEditor.setWindowTitle(QtGui.QApplication.translate("PatternRowRepeatEditor", "Pattern Row Repeat Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(PatternRowRepeatEditor)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.controlGrouper = QtGui.QGroupBox(PatternRowRepeatEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlGrouper.sizePolicy().hasHeightForWidth())
        self.controlGrouper.setSizePolicy(sizePolicy)
        self.controlGrouper.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controlGrouper.setObjectName(_fromUtf8("controlGrouper"))
        self.verticalLayout = QtGui.QVBoxLayout(self.controlGrouper)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.controlGrouper)
        self.label.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "<b>Active Row Repeats</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.repeatWidget = QtGui.QTableWidget(self.controlGrouper)
        self.repeatWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.repeatWidget.setAlternatingRowColors(True)
        self.repeatWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.repeatWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.repeatWidget.setRowCount(0)
        self.repeatWidget.setColumnCount(3)
        self.repeatWidget.setObjectName(_fromUtf8("repeatWidget"))
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "start row", None, QtGui.QApplication.UnicodeUTF8))
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.repeatWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "end row", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "# of repeats", None, QtGui.QApplication.UnicodeUTF8))
        self.repeatWidget.setHorizontalHeaderItem(2, item)
        self.repeatWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.repeatWidget.horizontalHeader().setDefaultSectionSize(80)
        self.repeatWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.repeatWidget)
        self.addRepeatButton = QtGui.QPushButton(self.controlGrouper)
        self.addRepeatButton.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "&Add New Row Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.addRepeatButton.setObjectName(_fromUtf8("addRepeatButton"))
        self.verticalLayout.addWidget(self.addRepeatButton)
        self.updateRepeatButton = QtGui.QPushButton(self.controlGrouper)
        self.updateRepeatButton.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "&Update Selected Row Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.updateRepeatButton.setObjectName(_fromUtf8("updateRepeatButton"))
        self.verticalLayout.addWidget(self.updateRepeatButton)
        self.deleteRepeatButton = QtGui.QPushButton(self.controlGrouper)
        self.deleteRepeatButton.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "&Delete Selected Row Repeat", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRepeatButton.setObjectName(_fromUtf8("deleteRepeatButton"))
        self.verticalLayout.addWidget(self.deleteRepeatButton)
        self.horizontalLayout_3.addWidget(self.controlGrouper)
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.entryGrouper = QtGui.QGroupBox(PatternRowRepeatEditor)
        self.entryGrouper.setEnabled(True)
        self.entryGrouper.setObjectName(_fromUtf8("entryGrouper"))
        self.gridLayout = QtGui.QGridLayout(self.entryGrouper)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.entryGrouper)
        self.label_2.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "Start Row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.startRowSpinner = QtGui.QSpinBox(self.entryGrouper)
        self.startRowSpinner.setMinimum(1)
        self.startRowSpinner.setMaximum(1000)
        self.startRowSpinner.setObjectName(_fromUtf8("startRowSpinner"))
        self.gridLayout.addWidget(self.startRowSpinner, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.entryGrouper)
        self.label_3.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "End Row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.endRowSpinner = QtGui.QSpinBox(self.entryGrouper)
        self.endRowSpinner.setMinimum(1)
        self.endRowSpinner.setMaximum(1000)
        self.endRowSpinner.setProperty("value", 1)
        self.endRowSpinner.setObjectName(_fromUtf8("endRowSpinner"))
        self.gridLayout.addWidget(self.endRowSpinner, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.entryGrouper)
        self.label_4.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "# Repeats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.repeatSpinner = QtGui.QSpinBox(self.entryGrouper)
        self.repeatSpinner.setMinimum(1)
        self.repeatSpinner.setMaximum(1000)
        self.repeatSpinner.setObjectName(_fromUtf8("repeatSpinner"))
        self.gridLayout.addWidget(self.repeatSpinner, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cancelButton = QtGui.QPushButton(self.entryGrouper)
        self.cancelButton.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.acceptButton = QtGui.QPushButton(self.entryGrouper)
        self.acceptButton.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setObjectName(_fromUtf8("acceptButton"))
        self.horizontalLayout.addWidget(self.acceptButton)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 2)
        self.horizontalLayout_3.addWidget(self.entryGrouper)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.closeButton = QtGui.QPushButton(PatternRowRepeatEditor)
        self.closeButton.setText(QtGui.QApplication.translate("PatternRowRepeatEditor", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PatternRowRepeatEditor)
        QtCore.QMetaObject.connectSlotsByName(PatternRowRepeatEditor)

    def retranslateUi(self, PatternRowRepeatEditor):
        item = self.repeatWidget.horizontalHeaderItem(0)
        item = self.repeatWidget.horizontalHeaderItem(1)
        item = self.repeatWidget.horizontalHeaderItem(2)

